pt-BR translation for State of HTML 2023 FAQ
Devographics/locale-pt-BR pull request #70
Opened 2023-10-04 17:46 UTC by vilaboim

2023-10-04 18:09 UTC, the-physicist commented on config.yml
> +    "vilaboim",
Aqui você deve retirar a vírgula após seu usuário porque não é necessária na última posição do vetor.

2023-10-04 18:47 UTC, the-physicist requested changes
Olá, @vilaboim. Obrigado pela contribuição!
Deixei algumas sugestões pra ti.

2023-10-04 18:47 UTC, the-physicist commented on surveys.yml
> +       [nosso post de anúncio](https://lea.verou.me/blog/2023/design-state-of-html/).
Tenta seguir [esse padrão](https://github.com/Devographics/locale-en-US/blob/main/surveys.yml) do arquivo `surveys.yml` original porque a ordem está diferente, é interessante manter a mesma ordem do arquivo original.

2023-10-05 00:08 UTC, vilaboim commented on surveys.yml
> +       [nosso post de anúncio](https://lea.verou.me/blog/2023/design-state-of-html/).
Done.

2023-10-05 02:57 UTC, the-physicist commented on surveys.yml
> +       [nosso post de anúncio](https://lea.verou.me/blog/2023/design-state-of-html/).
Valeu, vou aceitar aqui!

2023-10-05 02:57 UTC, merged